# -*- coding: utf-8 -*-
"""countdown-timer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kDQ-3_q2FYdHu45bzG6jb9uXv9vDdJiF

# **Countdown Timer Project:**
"""

import time
import sys

def countdown_timer(seconds):
    print(f"Timer started for {seconds} seconds...\n")

    for sec in range(seconds, -1, -1):
        mins, secs = divmod(sec, 60)  # MM:SS format
        time_format = f"{mins:02d}:{secs:02d}"

        sys.stdout.write(f"\r{time_format}")
        sys.stdout.flush()
        time.sleep(1)  # Wait for 1 second

    print("\nTime's Up!")

# User input for timer:
total_seconds = int(input("Enter time in seconds for countdown: "))
countdown_timer(total_seconds)