# -*- coding: utf-8 -*-
"""guess-user.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctL7kYvbY-sZmyd0ZBISepKZoPbINHIA

# **Guess the Number (User):**
"""

import random

print("Guess the number between 1 and 100!")

# generate random number:
number = random.randint(1, 100)

# using while loop:
while True:
    guess = int(input("Enter your guess number:"))
    if guess < number:
        print("Your guess is too low!")
    elif guess > number:
        print("Your guess is too high!")
    else:
      print("Congratulations You Got It Right!")
      break