# -*- coding: utf-8 -*-
"""guess-number-computer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h-SZqlJHGekRWqkDW21odLpV-Gk5VTNs

# **Project 2: Guess the Number Game from Computer**
"""

import random

def guess_the_number():
    """Project 2: Guess The Number Game By Computer."""
    number = random.randint(1, 100)
    guesses_left = 7

    # Welcome Message
    print("Welcome to the number guessing game!")
    print("I am thinking of a number between 1 and 100.")

    # Game Loop
    while guesses_left > 0:
        print(f"\nYou have {guesses_left} guesses left.")
        try:
            guess = int(input("Take a guess: "))
        except ValueError:
            print("Invalid Input: Please enter a number.")
            continue

        # Guess checking
        if guess < number:
            print("Oops! Too Low. Try again.")
        elif guess > number:
            print("Oops! Too High. Try again.")
        else:
            print(f"Congratulations! You guessed the number {number} correctly in {7 - guesses_left + 1} tries!")
            return

        guesses_left -= 1

    # If user fails to guess
    print(f"\nYou ran out of guesses! The correct number was {number}. Better luck next time!")

# Start the game
guess_the_number()