# -*- coding: utf-8 -*-
"""hangman-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D8E5HfZO8J3EdDZX6yqnQW3M61P4-DLY

# **Hangman Python Project:**
"""

# Project 5: Hangman Python Project



import random

words = ["karachi", "colab", "ramzan", "shehroz", "mangos", "orange", "turkey", "punjab"]

word = random.choice(words)
guessed_letters = []
attempts = 7

print("Welcome to Hangman Game!")
print("_ " * len(word))

while attempts > 0:
    guess = input("\nGuess a letter(k,c,r,s,m,o,t,p): ").lower()

    if len(guess) != 1 or not guess.isalpha():
        print("Please enter a single alphabet only!")
        continue

    if guess in guessed_letters:
        print("Oops! You already guessed this letter. Try another one.")
        continue

    guessed_letters.append(guess)

    if guess in word:
        print("Correct guess!")
    else:
        attempts -= 1
        print(f"Wrong guess! {attempts} attempts remaining.")

    # Displaying the word with guessed letters
    displayed_word = " ".join([letter if letter in guessed_letters else "_" for letter in word])
    print(displayed_word)

    # Checking if the player has guessed all letters
    if "_" not in displayed_word:
        print(f"Congratulations! You guessed the correct word: {word}")
        break

# If attempts become zero, the game is over
if attempts == 0:
    print(f"😢 Game over! The correct word was: {word}")