# -*- coding: utf-8 -*-
"""mad libs game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1290njZULTQDsAq8Z-gEmlchsNZFO6XD-

# **Mad Libs Python Project:**
"""

# Title of the story:
print("Welcome to the Logical & Moral Mad Libs Story!\n")

# user inputs:
thief_name = input("Ek chor ka naam likhein: ")
city = input("Ek city ka naam likhy: ")
rich_man = input("Ek ameer shakhs ka naam likhy: ")
object_stolen = input("Koi qeemti cheez jo chori hosakti hai (jaise sona, mobile, painting): ")
unexpected_find = input("Koi aisi cheez likhy jo chor ka irada badal dy chorri karny sy(jaise ek chotta bacha, quran, koi dua likhi hui etc): ")
realization = input("Koi ehsaas jo chor ko hota hai (jaise sharam, afsos, izzat ka ehsaas, Allah ka dar): ")

# story with user inputs:

story = f"""

            Ek raat, {thief_name} ne {city} ke sabse ameer insaan {rich_man} ke ghar chori karne ka plan banaya.
            Woh aista se andar gya aur andar ja kar usny qeemti cheez find karna shuroo ki.
            Usne {object_stolen} uthaya aur bhagny k ki ... lekin phir achanak uski nazar {unexpected_find} par pari!

            Jab usne us cheez ko dekha, uska dil ek dum badal gaya or woh usi jaga rookh gya.
            Usko {realization} mehsoos hua, aur usne socha, "Kya mai sirf paison ke liye apni zindagi barbaad kar raha hoon?"

            Uss din {thief_name} ne faisla kiya ke woh chori chod dega aur imaandari se har kaam kary ga.
            Usne woh qeemti cheezy waapis rakh di, aur us ghar se bina kuch churaye chala gaya...
            Agle din, usne ek naya safar shuru kiya,jo k aik **imaandari ka!** tha.

            Moral of the story: **Har insaan acha hota hai, bus sirf ek moka chahiye apny apko peehchanny ka or badalne ka!**

        """


# Print final story
print("\n--- Your Logical & Moral Story ---")
print(story)