# -*- coding: utf-8 -*-
"""password-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yHGQg8mXIClCTDmcg4_kbEl5lHsha955

# **Password Generator Python Project:**
"""

# Project 7: Password Generator Python Project

import random
import string

def generated_password(lenght = 12):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(lenght))
    return password

# users inputs:
lenght = int(input("Enter the lenght of your desired passowrd: "))

password = generated_password(lenght)
print("\nYour Desired Generated Passowrd:" , password)