# -*- coding: utf-8 -*-
"""rock-paper-scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NaDIJRadTnj2vUT5GaCS-V3cNJC_lTxw

# **Rock, Paper, Scissors Game:**
"""

import random

# Game Choices:
choices = ["rock", "paper", "scissors"]

# Player Choice:
player_choice = input("Enter your choice (rock, paper, scissors): ").lower()

# Computer Choice:
computer_choice = random.choice(choices)

# Winner Choices:
if player_choice == computer_choice:
   print(f"Both selected {player_choice}. It's a tie!")

elif player_choice == "rock" and computer_choice == "scissors":
    print(f"Player wins! {player_choice} beats {computer_choice}.")

elif player_choice == "paper" and computer_choice == "rock":
    print(f"Player wins! {player_choice} beats {computer_choice}.")

elif player_choice == "scissors" and computer_choice == "paper":
    print(f"Player wins! {player_choice} beats {computer_choice}.")

else:
    print(f"Computer wins! {computer_choice} beats {player_choice}.")